### ISSUE TITLE
Error on processing file

### ISSUE THREAD

**Issue by skyksandr** [skyderby/track-segmentation#5]
While uploading a file:
[09-27-32.CSV.zip](https://github.com/skyderby/track-scanner/files/2213044/09-27-32.CSV.zip)
App get following response:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

```
Exception on /api/v1/scan [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/app/tracksegmenter/views.py", line 11, in prediction
    processing_result = DataProcessor(posted_data).call()
  File "/opt/app/tracksegmenter/processing/data_processor.py", line 24, in call
    self.preprocess_data()
  File "/opt/app/tracksegmenter/processing/data_processor.py", line 35, in preprocess_data
    self.preprocessed_df = Preprocessor(self.raw_df).call()
  File "/opt/app/tracksegmenter/processing/preprocessing.py", line 36, in call
    df['altitude_std'] = (df['hMSL'].rolling(window='5s').std()).bfill().ffill()
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 6195, in rolling
    on=on, axis=axis, closed=closed)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/window.py", line 2052, in rolling
    return Rolling(obj, **kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/window.py", line 86, in __init__
    self.validate()
  File "/usr/local/lib/python3.6/site-packages/pandas/core/window.py", line 1087, in validate
    self._validate_monotonic()
  File "/usr/local/lib/python3.6/site-packages/pandas/core/window.py", line 1119, in _validate_monotonic
    "monotonic".format(formatted))
ValueError: index must be monotonic
```

**Comment by xird** [comment]
This is the same issue as https://github.com/skyderby/skyderby/issues/434

From line 5183 onward, there are timestamps in incorrect order.
